/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Wikiplay;

/**
 *
 * @author Endika
 */
public class MainFrame extends javax.swing.JFrame {

    public MainMenu menuScreen = new MainMenu(this);

    /**
     * Creates new form MainMenu
     */
    public MainFrame() {
        initComponents();
        this.setContentPane(menuScreen); //panel = panel you want to change too.
        this.repaint();             //Ensures that the frame swaps to the next panel and doesn't get stuck.
        this.revalidate();
    }

    public void changeToMenu() {
        initComponents();
        this.setContentPane(menuScreen);
        this.repaint();
        this.revalidate();
    }

    public void changeToCreationHost(String name) {
        HostCreationMenu hostCreationScreen = new HostCreationMenu(this,name);
        initComponents();
        this.setContentPane(hostCreationScreen);
        this.repaint();
        this.revalidate();
        this.repaint();
        this.revalidate();
    }

    public void changeToHost(String name) {
        Host hostScreen = new Host(this,name);
        initComponents();
        this.setContentPane(hostScreen);
        this.repaint();
        this.revalidate();
    }

    public void changeToListJoin(String name) {        
        JoinMenu joinmenu = new JoinMenu(this,name);
        initComponents();        
        this.setContentPane(joinmenu);
        this.repaint();
        this.revalidate();
        this.repaint();
        this.revalidate();
    }

    public void changeToJoin( String ip , String name) {
        Join joinScreen = new Join(this,ip , name);        
        initComponents();
        this.setContentPane(joinScreen);         
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setName("mainFrame"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
